version: "3.7"

networks:
    excut:

services:
    vos:
        image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
        container_name: vos
        ports:
            - 8890:8890
            - 1111:1111
        networks:
            - excut
        environment:
            DefaultQuery: "SELECT  DISTINCT ?g WHERE  { GRAPH ?g {?s ?p ?o} } ORDER BY  ?g"
            SPARQL_UPDATE: "true"
        volumes:
            - /Users/gmo7rng/PycharmProjects/kg-explainable-clustering/data/virtuoso/database:/data




