vos:
  image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
  container_name: vos
  environment:
    SPARQL_UPDATE: "true"
#  volumes:
#    - /GW/D5data-11/gadelrab/virtuoso/database:/data
  ports:
    - "8890:8890"
